In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("../data/processed/parcoursup_2026_enriched.csv")

# Exploration nouveau df enriched

In [4]:
df.shape

(24058, 39)

In [5]:
df.columns

Index(['session', 'id_etablissement', 'name_etablissement',
       'type_etablissement', 'type_formation', 'name_formation',
       'mentions_specialites', 'apprentissage', 'internat', 'amenagement',
       'Informations complémentaires', 'region', 'departement', 'commune',
       'link_formation', 'website_etablissement', 'short_name_formation',
       'is_apprentissage', 'internat_code', 'is_presentiel',
       'is_partiel_distance', 'is_full_distance', 'has_sport_amenagement',
       'has_artist_amenagement', 'has_other_amenagement', 'presentation',
       'criteres_entree', 'debouches_professionnels', 'poursuite_etudes',
       'frais_scolarite', 'frais_scolarite_boursiers', 'langues_options',
       'nb_places', 'formation_ouverte_boursiers', 'diplome_controle_par_etat',
       'formation_selective', 'epreuves_selection', 'frais_candidature',
       'frais_candidature_boursiers'],
      dtype='object')

In [ ]:
column_nan_count = df.isna().sum()
nan_percents = (df.isna().mean() * 100)

for col, count in column_nan_count.items():
    print(f"{col} NaN : {count}")

session NaN : 0
id_etablissement NaN : 0
name_etablissement NaN : 0
type_etablissement NaN : 0
type_formation NaN : 0
name_formation NaN : 0
mentions_specialites NaN : 0
apprentissage NaN : 14459
internat NaN : 23286
amenagement NaN : 0
Informations complémentaires NaN : 19534
region NaN : 51
departement NaN : 51
commune NaN : 124
link_formation NaN : 0
website_etablissement NaN : 0
short_name_formation NaN : 0
is_apprentissage NaN : 0
internat_code NaN : 0
is_presentiel NaN : 0
is_partiel_distance NaN : 0
is_full_distance NaN : 0
has_sport_amenagement NaN : 0
has_artist_amenagement NaN : 0
has_other_amenagement NaN : 0
presentation NaN : 20926
criteres_entree NaN : 21104
debouches_professionnels NaN : 20926
poursuite_etudes NaN : 20929
frais_scolarite NaN : 20926
frais_scolarite_boursiers NaN : 20926
langues_options NaN : 20926
nb_places NaN : 85
formation_ouverte_boursiers NaN : 0
diplome_controle_par_etat NaN : 0
formation_selective NaN : 0
epreuves_selection NaN : 22969
frais_candidature NaN : 23042
frais_candidature_boursiers NaN : 23042

In [9]:
column_nan_count = df.isna().sum()
nan_percents = round((df.isna().mean() * 100))

nan_summary = pd.DataFrame({
    "NaN_count": column_nan_count,
    "NaN_percent": nan_percents
})

print(nan_summary)

                              NaN_count  NaN_percent
session                               0          0.0
id_etablissement                      0          0.0
name_etablissement                    0          0.0
type_etablissement                    0          0.0
type_formation                        0          0.0
name_formation                        0          0.0
mentions_specialites                  0          0.0
apprentissage                     14459         60.0
internat                          23286         97.0
amenagement                           0          0.0
Informations complémentaires      19534         81.0
region                               51          0.0
departement                          51          0.0
commune                             124          1.0
link_formation                        0          0.0
website_etablissement                 0          0.0
short_name_formation                  0          0.0
is_apprentissage                      0          0.0
internat_code                         0          0.0
is_presentiel                         0          0.0
is_partiel_distance                   0          0.0
is_full_distance                      0          0.0
has_sport_amenagement                 0          0.0
has_artist_amenagement                0          0.0
has_other_amenagement                 0          0.0
presentation                      20926         87.0
criteres_entree                   21104         88.0
debouches_professionnels          20926         87.0
poursuite_etudes                  20929         87.0
frais_scolarite                   20926         87.0
frais_scolarite_boursiers         20926         87.0
langues_options                   20926         87.0
nb_places                            85          0.0
formation_ouverte_boursiers           0          0.0
diplome_controle_par_etat             0          0.0
formation_selective                   0          0.0
epreuves_selection                22969         95.0
frais_candidature                 23042         96.0
frais_candidature_boursiers       23042         96.0

In [11]:
df[["type_formation", "frais_scolarite", "nb_places"]].head(10)

,type_formation,frais_scolarite,nb_places
0,Formations des écoles d'ingénieurs,628 €,120.0
1,Formations des écoles d'ingénieurs,628 €,95.0
2,Formations des écoles d'ingénieurs,628 €,82.0
3,Formations des écoles d'ingénieurs,628 €,50.0
4,Formations des écoles d'ingénieurs,Français et UE : 2650 € / an - Hors UE : 4850 ...,160.0
5,Formations des écoles d'ingénieurs,178 €,25.0
6,Formations des écoles d'ingénieurs,628 €,35.0
7,Formations des écoles d'ingénieurs,628 €,148.0
8,Formations des écoles d'ingénieurs,628 € - Etudiants extracommunautaires,400.0
9,Formations des écoles d'ingénieurs,1980 euros,24.0

In [12]:
df[["presentation", "criteres_entree"]].head(3)

,presentation,criteres_entree
0,Le réseau Polytech regroupe 16 écoles publique...,Disposer de compétences en matière de communic...
1,Le réseau Polytech regroupe 16 écoles publique...,Disposer de compétences en matière de communic...
2,- Ecole publique d'ingénieurs en 5 ans à Nancy...,Disposer de compétences en matière de communic...