# Initialisation

In [1]:
import pandas as pd
from src.backend.vector_store import explode_chunks

In [2]:
df = pd.read_csv("../data/processed/parcoursup_2026_enriched_rag.csv")
df_sample = df.head(10).copy()

# Chunking sur échantillons
## Sur 10 lignes

In [3]:
df_chunks = explode_chunks(df_sample, text_col="rag_document", max_chars=2000)
df_chunks

,session,id_etablissement,name_etablissement,type_etablissement,type_formation,name_formation,mentions_specialites,apprentissage,internat,amenagement,...,formation_ouverte_boursiers,diplome_controle_par_etat,formation_selective,epreuves_selection,frais_candidature,frais_candidature_boursiers,rag_document,chunk_index,chunk_text,chunk_id
0,2026,0212108C,Polytech Dijon (21),Publics,Formations des écoles d'ingénieurs,Formation d'ingénieur Bac + 5 - Bac général,Formation d'ingénieur Bac + 5,NaN,NaN,"Enseignement en présentiel,Formations avec amé...",...,1.0,1.0,1.0,Tous les candidats inscrits au concours seront...,"60,00 €","0,00 €",Nom de la formation : Formation d'ingénieur Ba...,0,Nom de la formation : Formation d'ingénieur Ba...,0_0
1,2026,0212108C,Polytech Dijon (21),Publics,Formations des écoles d'ingénieurs,Formation d'ingénieur Bac + 5 - Bac général,Formation d'ingénieur Bac + 5,NaN,NaN,"Enseignement en présentiel,Formations avec amé...",...,1.0,1.0,1.0,Tous les candidats inscrits au concours seront...,"60,00 €","0,00 €",Nom de la formation : Formation d'ingénieur Ba...,1,présenter un projet.\nDisposer de compétences...,0_1
2,2026,0212108C,Polytech Dijon (21),Publics,Formations des écoles d'ingénieurs,Formation d'ingénieur Bac + 5 - Bac général,Formation d'ingénieur Bac + 5,NaN,NaN,"Enseignement en présentiel,Formations avec amé...",...,1.0,1.0,1.0,Tous les candidats inscrits au concours seront...,"60,00 €","0,00 €",Nom de la formation : Formation d'ingénieur Ba...,2,.\nLes diplômés Polytech exercent dans des sec...,0_2
3,2026,0492226D,Polytech Angers (49),Publics,Formations des écoles d'ingénieurs,Formation d'ingénieur Bac + 5 - Bac général,Formation d'ingénieur Bac + 5,NaN,NaN,"Enseignement en présentiel,Formations avec amé...",...,1.0,1.0,1.0,Tous les candidats inscrits au concours seront...,"60,00 €","0,00 €",Nom de la formation : Formation d'ingénieur Ba...,0,Nom de la formation : Formation d'ingénieur Ba...,1_0
4,2026,0492226D,Polytech Angers (49),Publics,Formations des écoles d'ingénieurs,Formation d'ingénieur Bac + 5 - Bac général,Formation d'ingénieur Bac + 5,NaN,NaN,"Enseignement en présentiel,Formations avec amé...",...,1.0,1.0,1.0,Tous les candidats inscrits au concours seront...,"60,00 €","0,00 €",Nom de la formation : Formation d'ingénieur Ba...,1,t présenter un projet.\nDisposer de compétence...,1_1
5,2026,0492226D,Polytech Angers (49),Publics,Formations des écoles d'ingénieurs,Formation d'ingénieur Bac + 5 - Bac général,Formation d'ingénieur Bac + 5,NaN,NaN,"Enseignement en présentiel,Formations avec amé...",...,1.0,1.0,1.0,Tous les candidats inscrits au concours seront...,"60,00 €","0,00 €",Nom de la formation : Formation d'ingénieur Ba...,2,).\nLes diplômés Polytech exercent dans des se...,1_2
6,2026,0542259M,EEIGM Nancy - Groupe INP (54),Publics,Formations des écoles d'ingénieurs,Formation d'ingénieur Bac + 5 - Bac général,Formation d'ingénieur Bac + 5,NaN,NaN,"Enseignement en présentiel,Formations avec amé...",...,1.0,1.0,1.0,Tous les candidats inscrits au concours seront...,"60,00 €","0,00 €",Nom de la formation : Formation d'ingénieur Ba...,0,Nom de la formation : Formation d'ingénieur Ba...,2_0
7,2026,0542259M,EEIGM Nancy - Groupe INP (54),Publics,Formations des écoles d'ingénieurs,Formation d'ingénieur Bac + 5 - Bac général,Formation d'ingénieur Bac + 5,NaN,NaN,"Enseignement en présentiel,Formations avec amé...",...,1.0,1.0,1.0,Tous les candidats inscrits au concours seront...,"60,00 €","0,00 €",Nom de la formation : Formation d'ingénieur Ba...,1,"cientifiques, technologiques et les démarches ...",2_1
8,2026,0542259M,EEIGM Nancy - Groupe INP (54),Publics,Formations des écoles d'ingénieurs,Formation d'ingénieur Bac + 5 - Bac général,Formation d'ingénieur Bac + 5,NaN,NaN,"Enseignement en présentiel,Formations avec amé...",...,1.0,1.0,1.0,Tous les candidats inscrits au concours seront...,"60,00 €","0,00 €",Nom de la formation : Formation d'ingénieur Ba...,2,"matiques, physique-chimie, numérique et scienc...",2_2
9,2026,0542307P,ENSGSI Nancy - Groupe INP (54),Publics,Formations des écoles d'ingénieurs,Formation d'ingénieur Bac + 5 - Bac général,Formation d'ingénieur Bac + 5,NaN,NaN,"Enseignement en présentiel,Formations avec amé...",...,1.0,1.0,1.0,Tous les candidats inscrits au concours seront...,"60,00 €","0,00 €",Nom de la formation : Formation d'ingénieur Ba...,0,Nom de la formation : Formation d'ingénieur Ba...,3_0
10,2026,0542307P,ENSGSI Nancy - Groupe INP (54),Publics,Formations des écoles d'ingénieurs,Formation d'ingénieur Bac + 5 - Bac général,Formation d'ingénieur Bac + 5,NaN,NaN,"Enseignement en présentiel,Formations avec amé...",...,1.0,1.0,1.0,Tous les candidats inscrits au concours seront...,"60,00 €","0,00 €",Nom de la formation : Formation d'ingénieur Ba...,1,es et compétences acquises\nSavoir travailler ...,3_1
11,2026,0542307P,ENSGSI Nancy - Groupe INP (54),Publics,Formations des écoles d'ingénieurs,Formation d'ingénieur Bac + 5 - Bac général,Formation d'ingénieur Bac + 5,NaN,NaN,"Enseignement en présentiel,Formations avec amé...",...,1.0,1.0,1.0,Tous les candidats inscrits au concours seront...,"60,00 €","0,00 €",Nom de la formation : Formation d'ingénieur Ba...,2,ieur\nLes sujets de l'épreuve écrite 2026 port...,3_2
12,2026,0597060D,IMT Nord Europe (Villeneuve-d'Ascq - 59),Publics,Formations des écoles d'ingénieurs,Formation d'ingénieur Bac + 5 - Bac général,Formation d'ingénieur Bac + 5,NaN,NaN,"Enseignement en présentiel,Formations avec amé...",...,1.0,1.0,1.0,Tous les candidats inscrits au concours seront...,"60,00 €","0,00 €",Nom de la formation : Formation d'ingénieur Ba...,0,Nom de la formation : Formation d'ingénieur Ba...,4_0
13,2026,0597060D,IMT Nord Europe (Villeneuve-d'Ascq - 59),Publics,Formations des écoles d'ingénieurs,Formation d'ingénieur Bac + 5 - Bac général,Formation d'ingénieur Bac + 5,NaN,NaN,"Enseignement en présentiel,Formations avec amé...",...,1.0,1.0,1.0,Tous les candidats inscrits au concours seront...,"60,00 €","0,00 €",Nom de la formation : Formation d'ingénieur Ba...,1,t présenter un projet.\nDisposer de compétence...,4_1
14,2026,0597060D,IMT Nord Europe (Villeneuve-d'Ascq - 59),Publics,Formations des écoles d'ingénieurs,Formation d'ingénieur Bac + 5 - Bac général,Formation d'ingénieur Bac + 5,NaN,NaN,"Enseignement en présentiel,Formations avec amé...",...,1.0,1.0,1.0,Tous les candidats inscrits au concours seront...,"60,00 €","0,00 €",Nom de la formation : Formation d'ingénieur Ba...,2,hématiques et à l’option maths complémentaires...,4_2
15,2026,0596610P,Polytech Lille BIO (Villeneuve-d'Ascq - 59),Publics,Formations des écoles d'ingénieurs,Formation d'ingénieur Bac + 5 - Bac général,Formation d'ingénieur Bac + 5,NaN,NaN,"Enseignement en présentiel,Formations avec amé...",...,1.0,1.0,1.0,Tous les candidats inscrits au concours seront...,"60,00 €","0,00 €",Nom de la formation : Formation d'ingénieur Ba...,0,Nom de la formation : Formation d'ingénieur Ba...,5_0
16,2026,0596610P,Polytech Lille BIO (Villeneuve-d'Ascq - 59),Publics,Formations des écoles d'ingénieurs,Formation d'ingénieur Bac + 5 - Bac général,Formation d'ingénieur Bac + 5,NaN,NaN,"Enseignement en présentiel,Formations avec amé...",...,1.0,1.0,1.0,Tous les candidats inscrits au concours seront...,"60,00 €","0,00 €",Nom de la formation : Formation d'ingénieur Ba...,1,e compétences écrites et orales en langues étr...,5_1
17,2026,0596610P,Polytech Lille BIO (Villeneuve-d'Ascq - 59),Publics,Formations des écoles d'ingénieurs,Formation d'ingénieur Bac + 5 - Bac général,Formation d'ingénieur Bac + 5,NaN,NaN,"Enseignement en présentiel,Formations avec amé...",...,1.0,1.0,1.0,Tous les candidats inscrits au concours seront...,"60,00 €","0,00 €",Nom de la formation : Formation d'ingénieur Ba...,2,dans des secteurs variés : sociétés de consei...,5_2
18,2026,0782104N,ISTY UVSQ Paris-Saclay (Mantes-la-Ville - 78),Publics,Formations des écoles d'ingénieurs,Formation d'ingénieur Bac + 5 - Bac général,Formation d'ingénieur Bac + 5,NaN,NaN,"Enseignement en présentiel,Formations avec amé...",...,1.0,1.0,1.0,Tous les candidats inscrits au concours seront...,"60,00 €","0,00 €",Nom de la formation : Formation d'ingénieur Ba...,0,Nom de la formation : Formation d'ingénieur Ba...,6_0
19,2026,0782104N,ISTY UVSQ Paris-Saclay (Mantes-la-Ville - 78),Publics,Formations des écoles d'ingénieurs,Formation d'ingénieur Bac + 5 - Bac général,Formation d'ingénieur Bac + 5,NaN,NaN,"Enseignement en présentiel,Formations avec amé...",...,1.0,1.0,1.0,Tous les candidats inscrits au concours seront...,"60,00 €","0,00 €",Nom de la formation : Formation d'ingénieur Ba...,1,étaux.\n\nDisposer de solides compétences scie...,6_1
20,2026,0782104N,ISTY UVSQ Paris-Saclay (Mantes-la-Ville - 78),Publics,Formations des écoles d'ingénieurs,Formation d'ingénieur Bac + 5 - Bac général,Formation d'ingénieur Bac + 5,NaN,NaN,"Enseignement en présentiel,Formations avec amé...",...,1.0,1.0,1.0,Tous les candidats inscrits au concours seront...,"60,00 €","0,00 €",Nom de la formation : Formation d'ingénieur Ba...,2,airement sur le programme de Terminale. Les pr...,6_2
21,2026,0570140T,ENIM Metz (57),Publics,Formations des écoles d'ingénieurs,Formation d'ingénieur Bac + 5 - Bac général,Formation d'ingénieur Bac + 5,NaN,NaN,"Enseignement en présentiel,Formations avec amé...",...,1.0,1.0,1.0,Tous les candidats inscrits au concours seront...,"60,00 €","0,00 €",Nom de la formation : Formation d'ingénieur Ba...,0,Nom de la formation : Formation d'ingénieur Ba...,7_0
22,2026,0570140T,ENIM Metz (57),Publics,Formations des écoles d'ingénieurs,Formation d'ingénieur Bac + 5 - Bac général,Formation d'ingénieur Bac + 5,NaN,NaN,"Enseignement en présentiel,Formations avec amé...",...,1.0,1.0,1.0,Tous les candidats inscrits au concours seront...,"60,00 €","0,00 €",Nom de la formation : Formation d'ingénieur Ba...,1,partir de connaissances et compétences acquise...,7_1
23,2026,0570140T,ENIM Metz (57),Publics,Formations des écoles d'ingénieurs,Formation d'ingénieur Bac + 5 - Bac général,Formation d'ingénieur Bac + 5,NaN,NaN,"Enseignement en présentiel,Formations avec amé...",...,1.0,1.0,1.0,Tous les candidats inscrits au concours seront...,"60,00 €","0,00 €",Nom de la formation : Formation d'ingénieur Ba...,2,rogrammes des révisions pour l'épreuve écrite ...,7_2
24,2026,0601223D,UTC Université de Technologie de Compiègne (60),Publics,Formations des écoles d'ingénieurs,Formation d'ingénieur Bac + 5 - Série générale,Formation d'ingénieur Bac + 5,NaN,NaN,"Enseignement en présentiel,Formations avec amé...",...,1.0,1.0,1.0,Un\ntest de niveau de langue en ligne sera eff...,"105,00 €","0,00 €",Nom de la formation : Formation d'ingénieur Ba...,0,Nom de la formation : Formation d'ingénieur Ba...,8_0
25,2026,0601223D,UTC Université de Technologie de Compiègne (60),Publics,Formations des écoles d'ingénieurs,Formation d'ingénieur Bac + 5 - Série générale,Formation d'ingénieur Bac + 5,NaN,NaN,"Enseignement en présentiel,Formations avec amé...",...,1.0,1.0,1.0,Un\ntest de niveau de langue en ligne sera eff...,"105,00 €","0,00 €",Nom de la formation : Formation d'ingénieur Ba...,1,ler à partir de documents originaux.\nDisposer...,8_1
26,2026,0601223D,UTC Université de Technologie de Compiègne (60),Publics,Formations des écoles d'ingénieurs,Formation d'ingénieur Bac + 5 - Série générale,Formation d'ingénieur Bac + 5,NaN,NaN,"Enseignement en présentiel,Formations avec amé...",...,1.0,1.0,1.0,Un\ntest de niveau de langue en ligne sera eff...,"105,00 €","0,00 €",Nom de la formation : Formation d'ingénieur Ba...,2,er les compétences linguistiques nécessaires p...,8_2
27,2026,0490075R,ESEO - Angers - Prépa Associée au lycée Mongaz...,Privés en contrat avec l’Etat / EESC,Formations des écoles d'ingénieurs,Formation d'ingénieur Bac + 5 - Bacs généraux ...,Formation d'ingénieur Bac + 5,NaN,NaN,"Enseignement en présentiel,Formations avec amé...",...,1.0,1.0,1.0,Le samedi 25 avril 2026 auront lieu\n3 épreuve...,"130,00 €","15,00 €",Nom de la formation : Formation d'ingénieur Ba...,0,Nom de la formation : Formation d'ingénieur Ba...,9_0
28,2026,0490075R,ESEO - Angers - Prépa Associée au lycée Mongaz...,Privés en contrat avec l’Etat / EESC,Formations des écoles d'ingénieurs,Formation d'ingénieur Bac + 5 - Bacs généraux ...,Formation d'ingénieur Bac + 5,NaN,NaN,"Enseignement en présentiel,Formations avec amé...",...,1.0,1.0,1.0,Le samedi 25 avril 2026 auront lieu\n3 épreuve...,"130,00 €","15,00 €",Nom de la formation : Formation d'ingénieur Ba...,1,ammes officiels CPGE\nPossibilité d’internat\n...,9_1
29,2026,0490075R,ESEO - Angers - Prépa Associée au lycée Mongaz...,Privés en contrat avec l’Etat / EESC,Formations des écoles d'ingénieurs,Formation d'ingénieur Bac + 5 - Bacs généraux ...,Formation d'ingénieur Bac + 5,NaN,NaN,"Enseignement en présentiel,Formations avec amé...",...,1.0,1.0,1.0,Le samedi 25 avril 2026 auront lieu\n3 épreuve...,"130,00 €","15,00 €",Nom de la formation : Formation d'ingénieur Ba...,2,adaptés à votre programme de terminale\nIl s'...,9_2

## Sur 200 lignes

In [4]:
# échantillon de 200 formations pour tester
df_sample_2 = df.head(200).copy()

df_chunks_2 = explode_chunks(df_sample_2, text_col="rag_document", max_chars=2000)

# vérifier quelques stats
df_chunks_2["chunk_index"].value_counts().sort_index()
df_chunks_2["chunk_text"].str.len().describe()

# regarder quelques exemples
df_chunks_2[["name_formation", "chunk_index", "chunk_text"]].head(10)

,name_formation,chunk_index,chunk_text
0,Formation d'ingénieur Bac + 5 - Bac général,0,Nom de la formation : Formation d'ingénieur Ba...
1,Formation d'ingénieur Bac + 5 - Bac général,1,présenter un projet.\nDisposer de compétences...
2,Formation d'ingénieur Bac + 5 - Bac général,2,.\nLes diplômés Polytech exercent dans des sec...
3,Formation d'ingénieur Bac + 5 - Bac général,0,Nom de la formation : Formation d'ingénieur Ba...
4,Formation d'ingénieur Bac + 5 - Bac général,1,t présenter un projet.\nDisposer de compétence...
5,Formation d'ingénieur Bac + 5 - Bac général,2,).\nLes diplômés Polytech exercent dans des se...
6,Formation d'ingénieur Bac + 5 - Bac général,0,Nom de la formation : Formation d'ingénieur Ba...
7,Formation d'ingénieur Bac + 5 - Bac général,1,"cientifiques, technologiques et les démarches ..."
8,Formation d'ingénieur Bac + 5 - Bac général,2,"matiques, physique-chimie, numérique et scienc..."
9,Formation d'ingénieur Bac + 5 - Bac général,0,Nom de la formation : Formation d'ingénieur Ba...

In [5]:
df_chunks_2["chunk_text"].str.len().describe()

count     306.000000
mean     1048.816993
std       769.487902
min        38.000000
25%       348.000000
50%       481.500000
75%      2000.000000
max      2000.000000
Name: chunk_text, dtype: float64